import PDFDocument from "pdfkit";

export const generateReportPDF = (report, res) => {
  const doc = new PDFDocument({ margin: 50 });

  // Set response headers
  res.setHeader("Content-Type", "application/pdf");
  res.setHeader(
    "Content-Disposition",
    `attachment; filename=medical_report_${report._id}.pdf`
  );

  doc.pipe(res);

  // Title
  doc.fontSize(20).text("Medical Prediction Report", { align: "center" });
  doc.moveDown();

  // Metadata
  doc.fontSize(12);
  doc.text(`Report ID: ${report._id}`);
  doc.text(`Generated On: ${new Date(report.createdAt).toLocaleString()}`);
  doc.moveDown();

  // Symptoms
  doc.fontSize(14).text("Symptoms Selected:");
  doc.moveDown(0.5);
  doc.fontSize(12);
  report.symptoms.forEach((symptom) => {
    doc.text(`• ${symptom}`);
  });

  doc.moveDown();

  // Predictions
  doc.fontSize(14).text("Predicted Diseases:");
  doc.moveDown(0.5);
  doc.fontSize(12);
  report.predictions.forEach((p) => {
    doc.text(`${p.disease} — ${p.probability}%`);
  });

  doc.moveDown();

  // Disclaimer
  doc
    .fontSize(10)
    .text(
      "Disclaimer: This report is generated by an AI-based decision-support system. Final diagnosis and treatment must be done by a certified medical professional.",
      { align: "justify" }
    );

  doc.end();
};
